device: '/dev/ttyUSB0'
baudrate: 115200
save_config: false
debug: false

slaves:
  nos:
    id: 1
    ms5837: true
    leds:
        led:
          id: 0
          timChId: 0
          smart: false

  nosovoi_sip:
    id: 2
    bcs:
      b1:
        id: 0
        timChId: 0
        dirGPIOChId: 0 # direction pin
        disGPIOChId: 1 # disable pin
        termGPIOChId: 2 # koncevik
        speed: 150
        neutral_position: 7000
        maximum_position: 15000 # positive buoyancy
        positive_direction: 0 # 0 or 1

  nosovaya_podrulka_vertikalnaya:
    id: 3
    thrusters:
      t1:
        id: 0
        timChId: 0
        deadzone: 5

  # nosovaya_podrulka_gorizontalnaya:
  #   id: 4
  #   thrusters:
  #     t1:
  #       id: 0
  #       timChId: 0
  #       deadzone: 3

  hvostovaya_podrulka_vertikalnaya:
    id: 5
    thrusters:
      t1:
        id: 0
        timChId: 0
        deadzone: 5

  # hvostovaya_podrulka_gorizontalnaya:
  #   id: 6
  #   thrusters:
  #     t1:
  #       id: 0
  #       timChId: 0
  #       deadzone: 3

  hvostoy_sip:
    id: 7
    bcs:
      b1:
        id: 0
        timChId: 0
        dirGPIOChId: 0 # direction pin
        disGPIOChId: 1 # disable pin
        termGPIOChId: 2 # koncevik
        speed: 150
        neutral_position: 7000
        maximum_position: 15000 # positive buoyancy
        positive_direction: 0 # 0 or 1

  hvost:
    id: 8
    ms5837: true
    thrusters:
      t1:
        id: 0
        timChId: 0
        deadzone: 3
      t2:
        id: 1
        timChId: 1
        deadzone: 3
    leds:
      led:
        id: 0
        timChId: 2
        smart: false


