device: '/dev/ttyUSB0'
baudrate: 115200
save_config: false
debug: false

slaves:
    nos:
        id: 1
        #thrusters:
            #t1:
                #timChId: 0
            #t2:
                #timChId: 1
        # leds:
            # l1:
            #     timChId: 0
                # smart: true
        bcs:
          b1:
                id: 0
                timChId: 0
                dirGPIOChId: 0 # direction pin
                disGPIOChId: 1 # disable pin
                termGPIOChId: 2 # koncevik
                speed: 200
                neutral_position: 1000
                maximum_position: 5000
                positive_direction: 0 # 0 or 1
    #hvost:
        #id: 2
        #bcs:
            #b1:
                #timChId: 0
                #dirGPIOChId: 0
                #disGPIOChId: 0
                #termGPIOChId: 0
    #seredina:
        #id: 3
        #bcs:
            #b2:
                #timChId: 1
                #dirGPIOChId: 0
                #disGPIOChId: 0
                #termGPIOChId: 0
