device: '/dev/ttyUSB0'
baudrate: 115200
debug: false
rate: 1

#thrusters:
    #t1:
        #slave: 1
        #id: 0
    #t2:
        #slave: 1
        #id: 1
    #t3:
        #slave: 2
        #id: 2
    #t4:
        #slave: 2
        #id: 3

#leds:
    #l1:
        #slave: 1
        #id: 0
    #l2:
        #slave: 1
        #id: 1

#bcs:
    #b1:
        #slave: 1
        #id: 0
    #b2:
        #slave: 1
        #id: 1

#ms5837:
    #slave: 2
